In [ ]:
import numpy as np

def fft_recursive(x):
    """
    x: Input array (1D) berupa bilangan kompleks atau real
    """
    N = len(x)
    
    # 1. Base Case: Jika N=1, return x
    if N <= 1:
        return x
    
    #Pisah Genap dan Ganjil
    even = fft_recursive(x[0::2])
    odd  = fft_recursive(x[1::2])
    
    k = np.arange(N // 2)
    T = np.exp(-2j* np.pi * k / N) * odd
    
    return np.concatenate([even + T, even - T])



In [4]:
a=fft_recursive([1,2,4,7])

In [5]:
a

array([14.+0.j, -3.+5.j, -4.+0.j, -3.-5.j])

In [6]:
def inverse_fft_recursive(x):
    N = len(x)
    if N<=1:
        return x
    
    even = inverse_fft_recursive(x[0::2])
    odd = inverse_fft_recursive(x[1::2])

    k = np.arange(N//2)
    T = np.exp(2j*np.pi * k / N) *odd

    return np.concatenate([even+T,even-T])

In [7]:
def inverse_fft(x):
    ans = inverse_fft_recursive(x)
    ans = ans/(len(x))
    return ans

In [8]:
inverse_fft(a)

array([1.+0.0000000e+00j, 2.-6.8963755e-17j, 4.+0.0000000e+00j,
       7.+6.8963755e-17j])

In [9]:
def multiplypolinoms(p1,p2):
    # p1 and p2 contains array of coefficients
    target_length = len(p1) + len(p2) -1

    n = 1
    while(n < target_length) :
        n*=2
    new_p1 = np.zeros(n)
    new_p2 = np.zeros(n)

    new_p1[:len(p1)] = p1
    new_p2[:len(p2)] = p2

    # 1. Convert to list of value DFT
    fft_p1 = fft_recursive(new_p1)
    fft_p2 = fft_recursive(new_p2)
    multiple = fft_p1 * fft_p2
    # for i in range (len(p1)):
    #     multiple[i] = fft_p1[i] * fft_p2[i]
    coeff = inverse_fft(multiple)
    coeff = coeff[:n-1]
    return coeff

In [10]:
import numpy as np

In [11]:
a = np.random.randint(300,size = int(2048))
b = np.random.randint(300,size = int(2048))

In [12]:
a,b

(array([ 31,  38,  38, ..., 175,  54, 155], shape=(2048,), dtype=int32),
 array([ 23, 261, 215, ..., 106,  83,  30], shape=(2048,), dtype=int32))

In [13]:
fft_style = multiplypolinoms(a,b)

In [14]:
fft_style

array([  713.00000001-1.69599730e-08j,  8965.00000001-1.61907641e-08j,
       17457.        -1.64049272e-08j, ...,
       26161.99999999+1.41804727e-09j, 14485.        -3.00341124e-09j,
        4650.        -3.40741829e-09j], shape=(4095,))

In [15]:
def manual_multiply_polinoms(p1,p2):
    n = len(p1) + len(p2) -1
    res = np.zeros(n)
    for i in range(len(p1)) :
        for j in range(len(p2)) :
            res[i+j] += p1[i] * p2[j]
    
    return res

In [16]:
from sklearn.metrics import mean_absolute_error


In [17]:
manual = manual_multiply_polinoms(a,b)

In [18]:
manual

array([  713.,  8965., 17457., ..., 26162., 14485.,  4650.], shape=(4095,))